/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <dlib/opencv.h>
#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>

/* Header for class com_example_lipstickdetect_FaceDetect */

// 定义命名空间
using namespace cv;
using namespace dlib;
using namespace std;

#ifndef _Included_com_example_lipstickdetect_FaceDetect
#define _Included_com_example_lipstickdetect_FaceDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lipstickdetect_FaceDetect
 * Method:    LandmarkDetection
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT jstring JNICALL Java_com_example_lipstickdetect_FaceDetect_LandmarkDetection
  (JNIEnv *, jclass, jlong,jlong);


//　声明两个方法
void renderToMat(std::vector<full_object_detection>& dets, Mat& dst);
std::string rgb2hex(int r,int g,int b);


#ifdef __cplusplus
}
#endif
#endif
