/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lipstickdetect_MainActivity */

#ifndef _Included_com_example_lipstickdetect_MainActivity
#define _Included_com_example_lipstickdetect_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lipstickdetect_MainActivity
 * Method:    getEdge
 * Signature: (Ljava/lang/Object;)V
 */

#ifdef __cplusplus
}
#endif
#endif
